FROM fedora:36

LABEL \
	org.opencontainers.image.title = "DPsim" \
	org.opencontainers.image.licenses = "MPL 2.0" \
	org.opencontainers.image.url = "http://dpsim.fein-aachen.org/" \
	org.opencontainers.image.source = "https://github.com/sogno-platform/dpsim"

RUN dnf -y update

# Toolchain
RUN dnf -y install \
	gcc gcc-c++ \
	git \
	make cmake pkgconfig \
	python3-pip

# Dependencies
RUN dnf --refresh -y install \
	python3-devel \
	eigen3-devel \
	spdlog-devel

# Python dependencies
ADD requirements.txt .
RUN pip3 install --upgrade wheel build setuptools packaging
RUN pip3 install -r requirements.txt

EXPOSE 8888
