FROM debian:11

ARG CIM_VERSION=CGMES_2.4.15_16FEB2016
ARG VILLAS_VERSION=c976cd62d8c6667a078be0785ca3e623a05f7456

ARG CMAKE_OPTS
ARG MAKE_OPTS=-j4

LABEL \
	org.opencontainers.image.title = "DPsim" \
	org.opencontainers.image.licenses = "MPL 2.0" \
	org.opencontainers.image.url = "http://dpsim.fein-aachen.org/" \
	org.opencontainers.image.source = "https://github.com/sogno-platform/dpsim"

RUN apt-get --assume-yes update

# Toolchain
RUN apt-get --assume-yes install \
	gcc g++ clang \
	git \
	make cmake pkg-config \
	python3-pip \
	wget

# Tools needed for developement
RUN apt-get --assume-yes install \
	doxygen graphviz \
	gdb

# Dependencies
RUN apt-get --assume-yes install \
	python3-dev \
	libeigen3-dev \
	libxml2-dev \
	libgraphviz-dev \
	libgsl-dev \
	libspdlog-dev \
	pybind11-dev \
	libspdlog-dev \
	libfmt-dev

# Build & Install sundials
RUN cd /tmp && \
	git clone --branch v3.2.1 --recurse-submodules --depth 1 https://github.com/LLNL/sundials.git && \
	mkdir -p sundials/build && cd sundials/build && \
	cmake ${CMAKE_OPTS} .. \
		-DCMAKE_BUILD_TYPE=Release && \
	make ${MAKE_OPTS} install

## Install minimal VILLASnode dependencies
RUN apt-get --assume-yes install \
	libssl-dev \
	uuid-dev \
	libcurl4-gnutls-dev \
	libjansson-dev \
	libwebsockets-dev

## Install optional VILLASnode dependencies
RUN apt-get --assume-yes install \
	libmosquitto-dev \
	libconfig-dev \
	libnl-3-dev

## Install libiec61850 from source
RUN cd /tmp && \
	wget https://libiec61850.com/wp-content/uploads/2019/03/libiec61850-1.3.3.tar.gz && \
	tar -zxvf libiec61850-1.3.3.tar.gz && rm libiec61850-1.3.3.tar.gz && \
	cd libiec61850-1.3.3 && \
	mkdir build && cd build && \
	cmake ${CMAKE_OPTS} .. \
		-DBUILD_SHARED_LIBS=ON && \
	make ${MAKE_OPTS} install && \
	rm -rf /tmp/libiec61850-1.3.3

## Python dependencies
ADD project.toml .
RUN pip3 install .[test,docs]

## Install CIMpp from source
RUN cd /tmp && \
	git clone --recurse-submodules --depth 1 https://github.com/cim-iec/libcimpp.git && \
	mkdir -p libcimpp/build && cd libcimpp/build && \
	cmake ${CMAKE_OPTS} .. \
		-DBUILD_SHARED_LIBS=ON \
		-DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
		-DUSE_CIM_VERSION=${CIM_VERSION} \
		-DBUILD_ARABICA_EXAMPLES=OFF && \
	make ${MAKE_OPTS} install && \
	rm -rf /tmp/libcimpp

## Install VILLASnode from source
RUN cd /tmp && \
	git clone --recurse-submodules https://github.com/VILLASframework/node.git villas-node && \
	mkdir -p villas-node/build && cd villas-node/build && \
	git checkout ${VILLAS_VERSION} && \
	cmake ${CMAKE_OPTS} .. \
		-DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
		-DDOWNLOAD_GO=OFF && \
	make install && \
	rm -rf /tmp/villas-node

# Remove this part in the future and use dedicated Jupyter Dockerfile
# Activate Jupyter extensions
RUN apt-get --assume-yes install \
	npm

RUN pip3 install \
	jupyter \
	jupyterlab \
	jupyter_contrib_nbextensions \
	nbconvert \
	nbformat

EXPOSE 8888
