stats = 1.0


nodes = {
	villas-matlab = {
		type = "socket",
		format = "raw",

		in = {
			address = "*:12008",

			signals = {
				count = 1
			}
		}

		out = {
			address = "137.226.133.227:12009"
		}
	},
	
	signal = {
		type = "signal"

		values = 1
		signal = "square"
		rate = 10
		frequency = 1
	}

}

paths = (
	{
		in = [
			"signal"
		],
		out = [
			"villas-matlab"
		]

		hooks = (
			{
				type = "limit_rate"
				rate = 10
			},
			"ts",
			"print"
		)
	}

)
