find_path(VILLASNODE_INCLUDE_DIR
	NAMES villas/node.hpp
)

find_library(VILLASNODE_LIBRARY
	NAMES villas
)

find_library(VILLASCOMMON_LIBRARY
	NAMES villas-common
)

find_library(VILLASFPGA_LIBRARY
	NAMES villas-fpga
)

set(VILLASNODE_LIBRARIES ${VILLASNODE_LIBRARY})
set(VILLASNODE_INCLUDE_DIRS ${VILLASNODE_INCLUDE_DIR})
set(VILLASCOMMON_LIBRARIES ${VILLASCOMMON_LIBRARY})
set(VILLASFPGA_LIBRARIES ${VILLASFPGA_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
	VILLASnode
	DEFAULT_MSG
	VILLASNODE_LIBRARY
	VILLASNODE_INCLUDE_DIR
	VILLASCOMMON_LIBRARY
)

message(STATUS "VILLAS include: ${VILLASNODE_INCLUDE_DIR}")
message(STATUS "VILLASnode library: ${VILLASNODE_LIBRARY}")
message(STATUS "VILLAScommon library: ${VILLASCOMMON_LIBRARY}")
message(STATUS "VILLASfpga library: ${VILLASFPGA_LIBRARY}")

mark_as_advanced(
	VILLASNODE_INCLUDE_DIR
	VILLASNODE_LIBRARY
	VILLASCOMMON_LIBRARY
	VILLASFPGA_LIBRARY
)
