find_path(SUITESPARSE_INCLUDE_DIR NAMES amd.h)
find_library(SUITESPARSE_AMD_LIBRARY NAMES amd)
find_library(SUITESPARSE_COLAMD_LIBRARY NAMES colamd)
find_library(SUITESPARSE_BTF_LIBRARY NAMES btf)
find_library(SUITESPARSE_KLU_LIBRARY NAMES klu)

set(SUITESPARSE_LIBRARIES ${SUITESPARSE_AMD_LIBRARY} ${SUITESPARSE_COLAMD_LIBRARY} ${SUITESPARSE_BTF_LIBRARY} ${SUITESPARSE_KLU_LIBRARY})
set(SUITESPARSE_INCLUDE_DIRS ${SUITESPARSE_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SuiteSparse DEFAULT_MSG SUITESPARSE_LIBRARIES SUITESPARSE_INCLUDE_DIR)

mark_as_advanced(SUITESPARSE_INCLUDE_DIR SUITESPARSE_LIBRARIES)

add_library(SuiteSparse::BTF STATIC IMPORTED)
set_property(TARGET SuiteSparse::BTF PROPERTY IMPORTED_LOCATION ${SUITESPARSE_BTF_LIBRARY})
target_include_directories(SuiteSparse::BTF INTERFACE ${SUITESPARSE_INCLUDE_DIR})

add_library(SuiteSparse::COLAMD STATIC IMPORTED)
set_property(TARGET SuiteSparse::COLAMD PROPERTY IMPORTED_LOCATION ${SUITESPARSE_COLAMD_LIBRARY})
target_include_directories(SuiteSparse::COLAMD INTERFACE ${SUITESPARSE_INCLUDE_DIR})

add_library(SuiteSparse::AMD STATIC IMPORTED)
set_property(TARGET SuiteSparse::AMD PROPERTY IMPORTED_LOCATION ${SUITESPARSE_AMD_LIBRARY})
target_include_directories(SuiteSparse::AMD INTERFACE ${SUITESPARSE_INCLUDE_DIR})

add_library(SuiteSparse::KLU STATIC IMPORTED)
set_property(TARGET SuiteSparse::KLU PROPERTY IMPORTED_LOCATION ${SUITESPARSE_KLU_LIBRARY})
target_include_directories(SuiteSparse::KLU INTERFACE ${SUITESPARSE_INCLUDE_DIR})

target_link_libraries(SuiteSparse::KLU INTERFACE
	SuiteSparse::AMD
	SuiteSparse::BTF
	SuiteSparse::COLAMD
)
