name: Run pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: sogno-platform-dpsim-runner
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - uses: pre-commit/action@v3.0.1
