# SPDX-FileCopyrightText: 2026 Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
# SPDX-License-Identifier: MPL-2.0

name: Prepare Images

on:
  workflow_call:
    inputs:
      ref:
        description: 'Revision to build the images from'
        required: true
        type: string
      tag:
        description: 'Slugified name of the revision under test'
        required: true
        type: string
      image_prefix:
        description: 'Registry path the images are pushed to'
        required: true
        type: string
      base_images:
        description: 'Images to build, as a JSON list of image and file pairs'
        required: true
        type: string
      derived_images:
        description: 'Images built on top of the development image, same format'
        required: true
        type: string
      base_image:
        description: 'Image the derived images are built from'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  base:
    name: Build ${{ matrix.image }} image
    if: inputs.base_images != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.base_images) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          cache-from: type=gha,scope=${{ matrix.image }}
          cache-to: type=gha,mode=min,scope=${{ matrix.image }}
          tags: |
            ${{ inputs.image_prefix }}/${{ matrix.image }}:${{ inputs.ref }}
            ${{ inputs.image_prefix }}/${{ matrix.image }}:${{ inputs.tag }}

  derived:
    name: Build ${{ matrix.image }} image
    needs: [base]
    if: ${{ always() && needs.base.result != 'failure' && inputs.derived_images != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.derived_images) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          build-args: |
            BASE_IMAGE=${{ inputs.base_image }}
          cache-from: type=gha,scope=${{ matrix.image }}
          cache-to: type=gha,mode=min,scope=${{ matrix.image }}
          tags: |
            ${{ inputs.image_prefix }}/${{ matrix.image }}:${{ inputs.ref }}
            ${{ inputs.image_prefix }}/${{ matrix.image }}:${{ inputs.tag }}
