# SPDX-FileCopyrightText: 2026 Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
# SPDX-License-Identifier: MPL-2.0

name: Publish to PyPI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Resolve Version
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version string
        id: get_version
        run: |
          REF_NAME="${{ github.ref_name }}"
          #testpypi resolution if tag push contains rc or wf is dispatched
          if [ "${{ github.event_name }}" = "workflow_dispatch" || "$REF_NAME" == *rc*]; then
            #this is dispatched over branch, fetch latest tag
            if [ "${{ github.ref_type}}" = "branch" ]; then
              TAG=$(git describe --tags --abbrev=0)
            #otherwise use pushed tag
            else
              TAG="$REF_NAME"
            fi

            #remove dash in case it contains rc ( publish fails )
            TAG=$(echo "$TAG" | tr -d'-')

            #if not rc, need modify string
            #increase fix number by one, add .dev<run_number>
            if [[ "$TAG" != *rc* ]]; then
TAG="$(echo "$TAG" | awk -F. '{print $1"."$2"."$3+1}').dev${{ github.run_number }}"
            fi
          #tag push without rc
          else
            TAG="$REF_NAME"
          fi
          echo "version=${TAG}" >> $GITHUB_OUTPUT

  build:
    name: Packaging
    needs: [version]
    uses: ./.github/workflows/packaging-python.yaml
    with:
      ref: ${{ github.sha }}
      version: ${{ needs.version.outputs.version }}
      image: sogno/dpsim:dev

  publish-testpypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    needs: [version, build]
    if: github.event_name == 'workflow_dispatch' || contains(github.ref, 'rc')
    steps:
    - name: Download wheels from build jobs
      uses: actions/download-artifact@v8
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist/

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.14.0
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-24.04
    if: github.event_name != 'workflow_dispatch' && !contains(github.ref, 'rc')
    environment: pypi
    permissions:
      id-token: write
    needs: [version, build]

    steps:
    - name: Download wheels from build jobs
      uses: actions/download-artifact@v8
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1.14.0
