name: Publish DPsim Windows package to Python Package Index (PyPI)

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-sdist:
    name: Build DPsim source distribution in Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install build tool
      run: python -m pip install --upgrade build

    - name: Build DPsim source distribution
      run: python -m build --sdist --outdir dist/

    - name: Archive Python source distribution
      uses: actions/upload-artifact@v4
      with:
        name: dist-source-win
        path: dist/

  build-wheels:
    name: Build DPsim Python wheel for Windows
    strategy:
      matrix:
        include:
          - os: windows-latest
            python: cp313
            arch: amd64
            cibw_arch: AMD64

          - os: windows-latest
            python: cp313
            arch: win32
            cibw_arch: x86

          - os: windows-latest
            python: cp313
            arch: win_arm64
            cibw_arch: ARM64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Build wheel
      uses: pypa/cibuildwheel@v2.23.2
      env:
        CIBW_BUILD: "${{ matrix.python }}-*"
        CIBW_ARCHS: "${{ matrix.cibw_arch }}"
        CIBW_ENVIRONMENT: >
          CMAKE_ARGS="-DWITH_PYBIND=ON -DCMAKE_VERBOSE_MAKEFILE=ON"
          CMAKE_BUILD_PARALLEL_LEVEL=4
      with:
        output-dir: dist

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.python }}-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/

  publish:
    name: Publish wheels and source distribution to PyPI
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'
    permissions:
      id-token: write
    needs:
    - build-wheels
    - build-sdist

    steps:
    - name: Download wheels from build jobs
      uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist/

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.12.4
